### PR TITLE
Use close_process_in to avoid a pileup of zombie uname processes

### LINKED ISSUE #4466: Uname process doesn't close when running in Linux OS
**Describe the bug**
Running semgrep CLI from Amazon Linux OS doesn't close the `uname` process what causes a memory leak.

**To Reproduce**
Run Semgrep CLI in Amazon Linux OS.
`uname` processes doesn't close.

**Expected behavior**
after semgrep process has finished - close all the relevant processes.

**Screenshots**
image

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Amazon Linux OS
Semgrep version 0.77.0

### PR DESCRIPTION
**Pull request by mjambon**
The use of lazy evaluation could save some resources, too.

This should fix https://github.com/returntocorp/semgrep/issues/4466

I haven't tested this but if regular semgrep tests pass, it should be fine.

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

File: commons_ocollection/ograph_extended.ml [hunk 1]
```diff
@@ -318,7 +323,7 @@ let launch_gv_cmd filename =
   ()
 
 let display_graph_cmd =
```
Comment (aryx) [inline commons_ocollection/ograph_extended.ml]: lazy will not save any resource. It will always be forced each time the ocaml program starts.
Maybe you also want to add a () parameter to display_graph_cmd so it's evaluated only when we actually need to launch gv.

**Review by aryx — APPROVED** [review]

File: commons_ocollection/ograph_extended.ml (hunk 1 above)
Comment (mjambon) [reply commons_ocollection/ograph_extended.ml]: should be fine now. They're now all normal function calls, with laziness under the hood.
